# Examen A Módulo 1 - Optimización.

**Lea cuidadosamente las siguientes indicaciones antes de comenzar el examen:**
- Para resolver el examen edite este mismo archivo y renómbrelo de la siguiente manera: *Examen1_ApellidoNombre*, donde *ApellidoNombre* corresponde a su apellido paterno con la inicial en mayúscula, seguido de su primer nombre con la inicial en mayúscula **sin tildes**. Por ejemplo, en mi caso el nombre del archivo sería *Examen1_MoralesGabriel*.
- Resuelva los puntos en el espacio provisto. Si requiere agregar más celdas para código o escritura, hágalo (`Esc`,`B`) o (`Esc`,`A`).
- Recuerde que también se está evaluando su capacidad de interpretar los resultados. Escriba sus interpretaciones/conclusiones en celdas utilizando *Markdown*.
- El formato de presentación de todo el examen en general debe ser adecuado. Use tamaños de letra, colores, etiquetas, etcétera.
- No se resuelven dudas de ningún tipo por los profesores de la asignatura. Por favor, absténgase de preguntar.
- Revise bien el tipo de examen. Sólo se le calificará si realiza el tipo de examen asignado.

## 1. Optimización de funciones con `Sympy`

Funciones permitidas: subs, solve, var, expresiones matemáticas

## 1-a


Un cine cobra 86 pesos la entrada estándar y 60 pesos la entrada a estudiantes. Una sala con capacidad para 120 personas se ocupó al 70\%. Los ingresos para esa función fueron de 6,600 MXN. ¿Cuántos estudiantes entraron?

### Datos

86 -- estandar -- x

60 -- estudiante -- y

120 personas al 70% --- 84 personas

ingresos -- 6,600


ecuación total

86x + 60y = 6,600

x + y = 84

In [7]:
import numpy as np
import sympy as sp

sp.var("x")
sp.var("y")

p = x + y - 84
i = 86*x + 60*y - 6600

#sustituir y
y_ec = sp.solve(p, y)[0]

y_ec


84 - x

In [8]:
# sustituir y en ec de ingresos

i_x = i.subs(y, y_ec)
i_x

26*x - 1560

In [9]:
s_x = sp.solve(i_x, x)
s_x

[60]

In [10]:
s_y = p.subs(x, s_x[0])
s_y

y - 24

In [11]:
s_yf = sp.solve(s_y, y)
s_yf

[24]

#### Resultados

De lo anterior se puede concluir que: 

x = 60 estándar.

y = 24 estudiantes.

Por lo que había 60 estándar y 24 estudiantes

### 1-b

El cine ofrece combos y opciones individuales. El combo 'amigos' tiene un costo de 156 MXN y consiste de 2 refrescos y unas palomitas. Existe también el combo 'nachos' que tiene un costo de 112 MXN y consiste de un refresco y una orden de nachos. Por separado el refresco tiene un costo de 60 MXN, las palomitas 58 MXN y los nachos 72 MXN. Se obtuvo un total de 6450 de ingresos en dulcería:

- 38 combos vendidos
- 70 refrescos vendidos
- 33 órdenes de palomitas grandes vendidas
- 16 órdenes de nachos vendidas

¿Cuántas personas compraron palomitas sueltas?

### Datos dinero

refresco -- r  -- 60 pesos

palomitas -- p -- 58 pesos

nachos -- n -- 72 pesos

CA --- 2r + p = 156 pesos

CN --- r + n = 112 pesos

ingresos -- 6450

### Datos cantidades

CA + CN = 38

refrescos = 700

palomitas = 33

nachos = 16


In [123]:
import numpy as np
import sympy as sp

sp.var("CA")
sp.var("CN")
sp.var("r")
sp.var("p")
sp.var("n")

costo = 156*CA + 112*CN + 60*r + 58*p + 72*n - 6450

combo = CA + CN - 38

totpal = CA + p - 33

totnac = CN + n - 16

totref = 2*CA + CN + r - 70

In [193]:
totnac2 = sp.solve(totnac, n)[0]
totref2 = sp.solve(totref, r)[0]
print(totnac2)
print(totref2)

16 - CN
-2*CA - CN + 70


In [197]:
combo_ca = sp.solve(combo, CN)[0]
totpal_ca = sp.solve(totpal, p)[0]

print("CN = ", combo_ca)
print("p = ", totpal_ca)

CN =  38 - CA
p =  33 - CA


In [199]:
totnac_ca = totnac2.subs(CN, combo_ca)
totnac_ca

CA - 22

In [201]:
totref_ca = totref2.subs(CN, combo_ca)
totref_ca

32 - CA

In [203]:
costo1 = costo.subs(CN, combo_ca)
costo2 = costo1.subs(p, totpal_ca)
costo3 = costo2.subs(n, totnac_ca)
costo4 = costo3.subs(r, totref_ca)
costo4

56 - 2*CA

In [209]:
resCA = sp.solve(costo4, CA)[0]
resCA

28

In [211]:
palomitas = totpal.subs(CA, resCA)
palomitas

p - 5

In [215]:
resf = sp.solve(palomitas, p)[0]
resf

5

#### Se vendieron 5 palomitas

## 2. Programación lineal

Una empresa produce costales de 3 tipos de fertilizantes para diferentes aplicaciones utilizando cuantro componentes químicos: azufre, potasio, fósforo y nitrógeno. La información de cada tonelada de fertilizante es:


<table>
  <tr>
      <th>Fertilizante</th>
      <th>Fósforo</th>
      <th>Azufre</th>
      <th>Potasio</th>
      <th>Nitrógeno</th>
      <th>Precio de venta </th>
  </tr>
  <tr>
      <td>A</td>
      <td>3 kg</td>
      <td>5 kg</td>
      <td>4 kg</td>
      <td>2 kg </td>
      <td>\$40000</td>
  </tr>
  <tr>
      <td>B</td>
      <td>4 kg</td>
      <td>3 kg</td>
      <td>2 kg</td>
      <td>1 kg</td>
      <td>\$50000</td>
  </tr>
  <tr>
      <td>C</td>
      <td>5 kg</td>
      <td>2 kg</td>
      <td>3 kg</td>
      <td>4 kg</td>
      <td>\$60000</td>
  </tr>

</table>

La máquina que se usa para mezclar el fertilizante C necesita mantenimiento y por lo tanto sólo puede mezclar 10 toneladas. Además, hay un pedido de 8 toneladas del fertilizante A.

Dado que en almacén se tienen 90 kg de fósforo, 120 kg de nitrógeno, 80 kg de azufre y 95 kg de potasio, ¿cuánto recomiendas que se mezcle de cada fertilizante? (Nota: No se permiten fracciones de toneladas)

### 1. Maximizar ganancia

### 2. Definir Variables

$ x_a - Fertilizante A $

$ x_b - Fertilizante B $

$ x_b - Fertilizante C $

### 3. Función costo

$ $ MAX f(x_a, x_b, x_c) = 40000x_a + 50000x_b + 60000x_c $ $

### 4. Restricciones

Fosforo $3A + 4B + 5C \leq 90 $

Azufre $5A + 3B + 2C \leq 80 $

Potasio $4A + 2B + 3C \leq 95 $

Nitrógeno $2A + 1B + 4C \leq 120 $

Mantenimiento $ C \leq 10 $

Pedido $ A \geq 8  $


In [31]:
import numpy as np
import scipy.optimize as opt

In [38]:
c = np.array ([-40000,
               -50000,
               -60000
              ])

aub = np.array ([
    [  3,    4,    5],
    [  5,    3,    2],
    [  4,    2,    3],
    [  2,    1,    4],
    [  0,    0,    1],
    [ -1,    0,    0]
    ])

bub = np.array ([
    90,
    80,
    85,
    120,
    10,
    -8
    ])

In [40]:
sol = opt.linprog(c, aub, bub, integrality = 1)

In [42]:
sol

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -1130000.0
              x: [ 8.000e+00  9.000e+00  6.000e+00]
            nit: -1
          lower:  residual: [ 8.000e+00  9.000e+00  6.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.000e+00  1.700e+01  7.100e+01
                              4.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
 mip_node_count: 1
 mip_dual_bound: -1130000.0
        mip_gap: 0.0

¿Cuál es el ingreso total?

In [45]:
total = sol.fun

In [47]:
total*-1

1130000.0

¿Cuánto fósforo quedó en almacén?

In [50]:
fosF = (sol.x[0]*3) + (sol.x[1]*4) + (sol.x[2]*5)
fosF

90.0

Se usó un total de 90 ton de fósforo y habían 90 existentes

In [53]:
90-90


0

## 3. Regresión lineal

Se quiere predecir la resistencia a la compresión de concreto en función de las proporciones de los componentes en la mezcla (cemento, arena, agua, agregado). La constructora que está realizando el análisis tiene datos históricos donde se registraron cantidades de materia y la resistencia medida:

In [57]:
import pandas as pd
data = {
    'Cemento (kg)': [350, 400, 300, 450, 380, 410, 320, 370, 390, 360, 
                     340, 430, 315, 405, 425, 345, 395, 355, 440, 310, 
                     385, 370, 425, 335],
    'Arena (kg)': [600, 550, 700, 500, 580, 540, 650, 590, 570, 610, 
                   630, 520, 660, 545, 530, 620, 560, 605, 515, 670, 
                   575, 590, 535, 625],
    'Agua (kg)': [180, 160, 200, 170, 175, 165, 185, 172, 170, 190, 
                  182, 165, 195, 175, 168, 180, 175, 185, 162, 198, 
                  178, 172, 170, 180],
    'Agregado (kg)': [1000, 1100, 950, 1200, 1050, 1150, 980, 1020, 1080, 970, 
                      990, 1120, 950, 1060, 1140, 990, 1040, 1010, 1160, 940, 
                      1070, 1030, 1110, 1025],
    'Resistencia a la compresión (MPa)': [35, 42, 30, 50, 38, 44, 32, 36, 40, 34, 
                                          33, 48, 31, 43, 47, 37, 41, 35, 49, 29, 
                                          39, 36, 45, 33]
}
data = pd.DataFrame(data)
data

Cemento (kg)  Arena (kg)  Agua (kg)  Agregado (kg)  \
0            350         600        180           1000   
1            400         550        160           1100   
2            300         700        200            950   
3            450         500        170           1200   
4            380         580        175           1050   
5            410         540        165           1150   
6            320         650        185            980   
7            370         590        172           1020   
8            390         570        170           1080   
9            360         610        190            970   
10           340         630        182            990   
11           430         520        165           1120   
12           315         660        195            950   
13           405         545        175           1060   
14           425         530        168           1140   
15           345         620        180            990   
16           395         560        175           1040   
17           355         605        185           1010   
18           440         515        162           1160   
19           310         670        198            940   
20           385         575        178           1070   
21           370         590        172           1030   
22           425         535        170           1110   
23           335         625        180           1025   

    Resistencia a la compresión (MPa)  
0                                  35  
1                                  42  
2                                  30  
3                                  50  
4                                  38  
5                                  44  
6                                  32  
7                                  36  
8                                  40  
9                                  34  
10                                 33  
11                                 48  
12                                 31  
13                                 43  
14                                 47  
15                                 37  
16                                 41  
17                                 35  
18                                 49  
19                                 29  
20                                 39  
21                                 36  
22                                 45  
23                                 33

Ajusta un modelo utilizando mínimos cuadrados para encontrar una función que pueda predecir la resistencia del concreto.

In [60]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt

In [61]:
y = data["Resistencia a la compresión (MPa)"]
x1 = data["Cemento (kg)"]
x2 = data["Arena (kg)"]
x3 = data["Agua (kg)"]
x4 = data["Agregado (kg)"]

n = len(y)
ones = np.ones([n, 1])
xo1 = np.reshape(x1, [n, 1])
xo2 = np.reshape(x2, [n, 1])
xo3 = np.reshape(x3, [n, 1])
xo4 = np.reshape(x4, [n, 1])
X = np.hstack((ones, xo1, xo2, xo3, xo4))
y_vec = np.reshape(y,[n, 1])

In [62]:
X, y_vec

(array([[1.000e+00, 3.500e+02, 6.000e+02, 1.800e+02, 1.000e+03],
        [1.000e+00, 4.000e+02, 5.500e+02, 1.600e+02, 1.100e+03],
        [1.000e+00, 3.000e+02, 7.000e+02, 2.000e+02, 9.500e+02],
        [1.000e+00, 4.500e+02, 5.000e+02, 1.700e+02, 1.200e+03],
        [1.000e+00, 3.800e+02, 5.800e+02, 1.750e+02, 1.050e+03],
        [1.000e+00, 4.100e+02, 5.400e+02, 1.650e+02, 1.150e+03],
        [1.000e+00, 3.200e+02, 6.500e+02, 1.850e+02, 9.800e+02],
        [1.000e+00, 3.700e+02, 5.900e+02, 1.720e+02, 1.020e+03],
        [1.000e+00, 3.900e+02, 5.700e+02, 1.700e+02, 1.080e+03],
        [1.000e+00, 3.600e+02, 6.100e+02, 1.900e+02, 9.700e+02],
        [1.000e+00, 3.400e+02, 6.300e+02, 1.820e+02, 9.900e+02],
        [1.000e+00, 4.300e+02, 5.200e+02, 1.650e+02, 1.120e+03],
        [1.000e+00, 3.150e+02, 6.600e+02, 1.950e+02, 9.500e+02],
        [1.000e+00, 4.050e+02, 5.450e+02, 1.750e+02, 1.060e+03],
        [1.000e+00, 4.250e+02, 5.300e+02, 1.680e+02, 1.140e+03],
        [1.000e+00, 3.450

In [63]:
n, p = X.shape
beta = np.random.rand(p)

def fn(beta, X, y):
    beta = np.reshape(beta, [p, 1])
    y_pred = X@beta
    error = y_pred-y
    rss = error.T@error
    return rss

rss = opt.minimize(fn, beta, args=(X, y_vec))
rss

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 29.8498916805912
        x: [-5.576e+01  1.374e-01  2.436e-02  1.949e-02  2.397e-02]
      nit: 12
      jac: [ 0.000e+00  4.768e-07  2.384e-07  0.000e+00  2.384e-07]
 hess_inv: [[ 4.516e+02 -5.329e-01 ...  1.504e-01 -3.510e-03]
            [-5.329e-01  8.619e-04 ... -4.440e-04 -9.387e-05]
            ...
            [ 1.504e-01 -4.440e-04 ...  1.187e-03  8.075e-05]
            [-3.510e-03 -9.387e-05 ...  8.075e-05  4.317e-05]]
     nfev: 156
     njev: 26

¿Qué efecto tiene cada factor en la resistencia de la mezcla?

Los distintos factores afectan demasiado en la resistencia de la mezcla, ya que cada componente son las variables independientes y la Y que sería la resistencia es la variable dependiente.

La cantidad de agua, cemento, agregados afectan al resultado final.

¿Cuál será la resistencia si mezclo 390 kg de cemento, 570 kg de arena, 170 kg de agua y 1080 kg de agregado?

In [71]:
Resistencia = rss.x[0] + (rss.x[1]*390) + (rss.x[2]*570) + (rss.x[3]*170) + (rss.x[4]*1080) 
Resistencia

40.90572546084262

## 4. Regresión logística

Un equipo de ingenieros quiere saber si una muestra de concreto hidráulico fallará o no bajo determinadas condiciones, basándose en experiencias pasadas.

<table>
  <thead>
    <tr>
      <th>Resistencia a la compresión (MPa)</th>
      <th>Edad del concreto (días)</th>
      <th>Relación agua-cemento</th>
      <th>Falla (Sí/No)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>25</td>
      <td>28</td>
      <td>0.45</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>40</td>
      <td>56</td>
      <td>0.35</td>
      <td>No</td>
    </tr>
    <tr>
      <td>30</td>
      <td>28</td>
      <td>0.50</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>50</td>
      <td>90</td>
      <td>0.30</td>
      <td>No</td>
    </tr>
    <tr>
      <td>35</td>
      <td>28</td>
      <td>0.40</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>55</td>
      <td>120</td>
      <td>0.32</td>
      <td>No</td>
    </tr>
    <tr>
      <td>45</td>
      <td>60</td>
      <td>0.36</td>
      <td>No</td>
    </tr>
    <tr>
      <td>20</td>
      <td>7</td>
      <td>0.55</td>
      <td>Sí</td>
    </tr>
  </tbody>
</table>


1. ¿Qué factor afecta más? (Utiliza un vector de ceros como tu beta inicial)

In [76]:
Res = [25, 40, 30, 50, 35, 55, 45, 20]
Edad = [28, 56, 28, 90, 28, 120, 60, 7]
Rel  = [.45, .35, .5, .3, .4, .32, .36, .55]
Falla = [1, 0, 1, 0, 1, 0, 0, 1]

In [78]:
n = len(Falla)
ones = np.ones([n, 1])
ResR = np.reshape(Res, [n, 1])
EdadR = np.reshape(Edad, [n, 1])
RelR = np.reshape(Rel, [n, 1])
X = np.hstack([ones, ResR, EdadR, RelR])
X

array([[  1.  ,  25.  ,  28.  ,   0.45],
       [  1.  ,  40.  ,  56.  ,   0.35],
       [  1.  ,  30.  ,  28.  ,   0.5 ],
       [  1.  ,  50.  ,  90.  ,   0.3 ],
       [  1.  ,  35.  ,  28.  ,   0.4 ],
       [  1.  ,  55.  , 120.  ,   0.32],
       [  1.  ,  45.  ,  60.  ,   0.36],
       [  1.  ,  20.  ,   7.  ,   0.55]])

In [94]:
y_vec = np.reshape(Falla, (n, 1))
y_vec

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1]])

In [177]:
def prediccion(beta, X):
    return 1/(1+np.exp(-X@beta))

def J(beta, X, y):
    eps = 1e-10
    n, p = X.shape
    beta = np.reshape(beta, [p , 1])
    y_pred = prediccion(beta, X)
    e = y*np.log(y_pred + eps) + (1-y) * np.log(1 - y_pred + eps)
    return-np.sum(e)

beta = [0, 0, 0, 0]
rrs = opt.minimize(J, beta, args=(X, y_vec))
rrs

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 3.694208075913603e-07
        x: [ 2.007e+01  2.134e+00 -2.272e+00  1.284e+01]
      nit: 26
      jac: [ 2.235e-08  4.508e-06  6.996e-06 -1.490e-08]
 hess_inv: [[ 1.637e+06  1.576e+05 -1.723e+05  1.047e+06]
            [ 1.576e+05  1.517e+04 -1.659e+04  1.008e+05]
            [-1.723e+05 -1.659e+04  1.814e+04 -1.102e+05]
            [ 1.047e+06  1.008e+05 -1.102e+05  6.694e+05]]
     nfev: 150
     njev: 30

2. Calcula la probabilidad de falla para una muestra con las siguientes características:
- Resistencia a la compresión: 38 MPa
- Edad del concreto: 30 días
- Relación agua-cemento: 0.40

In [180]:
info = (rrs.x[0] + rrs.x[1]*38 + rrs.x[2]*30 + rrs.x[3]*.4)
info

38.13082265129149

In [182]:
res = 1/(1+np.exp(-info))
res

1.0

#### 1 = Fallará